SS13 form conversion
Moomoobeef/ss14-forms-txt pull request #19
Opened 2024-09-18 03:02 UTC by RHudson94

I converted a few forms from the ss13 paradise station wiki

2024-09-22 05:41 UTC, Moomoobeef commented
in addition to all the file-specific comments. Most of these files lack a label. You know that
`# Document Title` thingy at the top of every file in the repo? That is so that printers will label the paper when printing. So add those where they are missing.

2024-09-22 06:14 UTC, Ruinedbun commented
Added labels to all of them, but I'm not sure what you mean by file-specific comments.

2024-09-22 06:21 UTC, Moomoobeef commented
> Added labels to all of them, but I'm not sure what you mean by file-specific comments.

I just meant all the reviews left on files themselves

2024-09-22 06:24 UTC, Ruinedbun reviewed
Converted some ss13 forms, from the paradise station wiki

2024-09-22 06:29 UTC, Ruinedbun reviewed
Reviewed all files

2024-10-10 23:19 UTC, Moomoobeef requested changes
oh my god. The review comments I made were pending this whole time and you couldn't see them. I feel like such an idiot I'm so sorry!

Also I noticed you added document titles, but they need to have a space between the '#' and the text:
`# label` is good
`#label` is not

Again, sorry about the fuckup on my part!! I feel like an ass

2024-10-10 23:43 UTC, Ruinedbun commented on Practical-Forms/Mechsuit requisition form.txt
> +                                ╔══════════════════╗[/color]
May want to check this one yourself but it should be fixed

2024-10-10 23:47 UTC, Ruinedbun commented on Det Forms/Witness Deposition.txt
> +[italic][color=#aaaaaa]I, [color=#1b67a5] Sample[/color] , do affirm that the information above is true and correct to the best of my knowledge and relayed to the best of my ability. By signing below
I don't know if there is actual lore regarding this so I removed the SolGov reference.

2024-10-10 23:47 UTC, Ruinedbun commented on Det Forms/Witness Deposition.txt
> +                                [color=#1b487e]╔══════════════════╗[/color]
Should be fixed and look better.

2024-10-10 23:57 UTC, Ruinedbun commented on Fun/Psychologist's Assessment.txt
> +                               Evaluation[/color][/bold][/head]
This one may still need work, I don't have a good eye for alignment.

2024-10-11 00:10 UTC, Ruinedbun commented on HoP Paperwork/Demotion Form.txt
Removed the station fill-in and spaces aswell as clarified where name and position are to be written in place of sample

2024-10-11 00:13 UTC, Ruinedbun commented on Legal-Forms/Cyborgification Release.txt
> +                                [head=1]Form NT-67M[/head]
Fixed

2024-10-11 00:18 UTC, Ruinedbun commented on Legal-Forms/Execution Order.txt
> +                                [head=1][color=#1b487e]Current Station[/color]
fixed

2024-10-11 00:30 UTC, Ruinedbun commented on Legal-Forms/Termination of Contract.txt
If you decide to keep this it has been fixed

2024-10-11 00:35 UTC, Ruinedbun reviewed
Alright all comments with issues should be addressed and fixed.

2024-10-11 01:10 UTC, Ruinedbun commented on Legal-Forms/Prisoner Orientation Form.txt
This took effort but should properly render now

2024-10-11 01:11 UTC, Ruinedbun commented on Legal-Forms/Quick Crime.txt
I like this better than what I had

2025-05-23 09:43 UTC, Moomoobeef commented
![image](https://github.com/user-attachments/assets/8c6251ec-7177-481b-a8dd-0322fd0bb8c0)
ouch. sorry I took so long

2025-05-23 09:44 UTC, Moomoobeef approved these changes
:+1:

2025-05-23 09:44 UTC, merged